with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
packages:
    github.com/chistyakoviv/converter/internal/http-server/handlers:
        interfaces:
            Validator:
    github.com/chistyakoviv/converter/internal/service:
        interfaces:
            ConversionQueueService:
            DeletionQueueService:
            TaskService:
            ConverterService:
    github.com/chistyakoviv/converter/internal/repository:
        # package-specific config here
        config:
        interfaces:
            ConversionQueueRepository:
                # package-level config for this specific interface (if applicable)
                config:
            DeletionQueueRepository:
    github.com/chistyakoviv/converter/internal/db:
        interfaces:
            TxManager:
    github.com/chistyakoviv/converter/internal/converter:
        interfaces:
            ImageConverter:
            VideoConverter: