services:
  converter:
    build:
      dockerfile: ./docker/development/converter/Dockerfile
    volumes:
      - ./:/go/src/github.com/chistyakoviv/converter
    # entr should be started with tty, otherwise it requires -n flag
    # see the error: 'entr: unable to get terminal attributes, use '-n' to run non-interactively'
    tty: true
    ports:
      - 80:8080 # http
    # environment:
      # - 'VIDEO_DEFAULT_FORMATS="[{"ext": "webm", optional": {"replace_orig_ext": true}, "conv_conf": {"c:v": "libvpx-vp9", "c:a": "libopus", "b:v": "1M", "b:a": "128k"}}]"'

  go-cli:
    image: golang:1.23.2-alpine3.20
    volumes:
      - ./:/go/src/github.com/chistyakoviv/converter
    working_dir: /go/src/github.com/chistyakoviv/converter

  converter-pg:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  converter-migrator:
    build:
      dockerfile: ./docker/development/migrator/Dockerfile
    volumes:
      - ./:/app
    environment:
      - PG_DSN=postgres://app:secret@converter-pg/app?sslmode=disable
      - GOOSE_MIGRATION_DIR=./migrations
    command: make converter-migrate-up