services:
  converter:
    build:
      dockerfile: ./docker/development/converter/Dockerfile
    volumes:
      - ./:/go/src/github.com/chistyakoviv/converter
    # entr should be started with tty, otherwise it requires -n flag
    # see the error: 'entr: unable to get terminal attributes, use '-n' to run non-interactively'
    tty: true
    ports:
      - 80:80 # http
      - 6060:6060 # pprof metrics
    environment:
      CONFIG_PATH: config/local.yml
      DEFAULTS_PATH: config/defaults.yml

  converter-pg:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  go-cli:
    build:
      dockerfile: ./docker/development/go-cli/Dockerfile
    volumes:
      - ./:/go/src/github.com/chistyakoviv/converter
    environment:
      - PG_DSN=postgres://app:secret@converter-pg/app?sslmode=disable
      - GOOSE_MIGRATION_DIR=./migrations