// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// IsScanning provides a mock function with no fields
func (_m *MockTaskService) IsScanning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsScanning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_IsScanning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScanning'
type MockTaskService_IsScanning_Call struct {
	*mock.Call
}

// IsScanning is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) IsScanning() *MockTaskService_IsScanning_Call {
	return &MockTaskService_IsScanning_Call{Call: _e.mock.On("IsScanning")}
}

func (_c *MockTaskService_IsScanning_Call) Run(run func()) *MockTaskService_IsScanning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_IsScanning_Call) Return(_a0 bool) *MockTaskService_IsScanning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_IsScanning_Call) RunAndReturn(run func() bool) *MockTaskService_IsScanning_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessImageQueues provides a mock function with given fields: ctx
func (_m *MockTaskService) ProcessImageQueues(ctx context.Context) {
	_m.Called(ctx)
}

// MockTaskService_ProcessImageQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessImageQueues'
type MockTaskService_ProcessImageQueues_Call struct {
	*mock.Call
}

// ProcessImageQueues is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) ProcessImageQueues(ctx interface{}) *MockTaskService_ProcessImageQueues_Call {
	return &MockTaskService_ProcessImageQueues_Call{Call: _e.mock.On("ProcessImageQueues", ctx)}
}

func (_c *MockTaskService_ProcessImageQueues_Call) Run(run func(ctx context.Context)) *MockTaskService_ProcessImageQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_ProcessImageQueues_Call) Return() *MockTaskService_ProcessImageQueues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskService_ProcessImageQueues_Call) RunAndReturn(run func(context.Context)) *MockTaskService_ProcessImageQueues_Call {
	_c.Run(run)
	return _c
}

// ProcessScanfs provides a mock function with given fields: ctx, rootDir
func (_m *MockTaskService) ProcessScanfs(ctx context.Context, rootDir string) error {
	ret := _m.Called(ctx, rootDir)

	if len(ret) == 0 {
		panic("no return value specified for ProcessScanfs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, rootDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_ProcessScanfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessScanfs'
type MockTaskService_ProcessScanfs_Call struct {
	*mock.Call
}

// ProcessScanfs is a helper method to define mock.On call
//   - ctx context.Context
//   - rootDir string
func (_e *MockTaskService_Expecter) ProcessScanfs(ctx interface{}, rootDir interface{}) *MockTaskService_ProcessScanfs_Call {
	return &MockTaskService_ProcessScanfs_Call{Call: _e.mock.On("ProcessScanfs", ctx, rootDir)}
}

func (_c *MockTaskService_ProcessScanfs_Call) Run(run func(ctx context.Context, rootDir string)) *MockTaskService_ProcessScanfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_ProcessScanfs_Call) Return(_a0 error) *MockTaskService_ProcessScanfs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_ProcessScanfs_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_ProcessScanfs_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessVideoQueues provides a mock function with given fields: ctx
func (_m *MockTaskService) ProcessVideoQueues(ctx context.Context) {
	_m.Called(ctx)
}

// MockTaskService_ProcessVideoQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessVideoQueues'
type MockTaskService_ProcessVideoQueues_Call struct {
	*mock.Call
}

// ProcessVideoQueues is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) ProcessVideoQueues(ctx interface{}) *MockTaskService_ProcessVideoQueues_Call {
	return &MockTaskService_ProcessVideoQueues_Call{Call: _e.mock.On("ProcessVideoQueues", ctx)}
}

func (_c *MockTaskService_ProcessVideoQueues_Call) Run(run func(ctx context.Context)) *MockTaskService_ProcessVideoQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_ProcessVideoQueues_Call) Return() *MockTaskService_ProcessVideoQueues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskService_ProcessVideoQueues_Call) RunAndReturn(run func(context.Context)) *MockTaskService_ProcessVideoQueues_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function with no fields
func (_m *MockTaskService) Shutdown() {
	_m.Called()
}

// MockTaskService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTaskService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) Shutdown() *MockTaskService_Shutdown_Call {
	return &MockTaskService_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockTaskService_Shutdown_Call) Run(run func()) *MockTaskService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_Shutdown_Call) Return() *MockTaskService_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskService_Shutdown_Call) RunAndReturn(run func()) *MockTaskService_Shutdown_Call {
	_c.Run(run)
	return _c
}

// TryQueueImageConversion provides a mock function with no fields
func (_m *MockTaskService) TryQueueImageConversion() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TryQueueImageConversion")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_TryQueueImageConversion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryQueueImageConversion'
type MockTaskService_TryQueueImageConversion_Call struct {
	*mock.Call
}

// TryQueueImageConversion is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) TryQueueImageConversion() *MockTaskService_TryQueueImageConversion_Call {
	return &MockTaskService_TryQueueImageConversion_Call{Call: _e.mock.On("TryQueueImageConversion")}
}

func (_c *MockTaskService_TryQueueImageConversion_Call) Run(run func()) *MockTaskService_TryQueueImageConversion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_TryQueueImageConversion_Call) Return(_a0 bool) *MockTaskService_TryQueueImageConversion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_TryQueueImageConversion_Call) RunAndReturn(run func() bool) *MockTaskService_TryQueueImageConversion_Call {
	_c.Call.Return(run)
	return _c
}

// TryQueueImageDeletion provides a mock function with no fields
func (_m *MockTaskService) TryQueueImageDeletion() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TryQueueImageDeletion")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_TryQueueImageDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryQueueImageDeletion'
type MockTaskService_TryQueueImageDeletion_Call struct {
	*mock.Call
}

// TryQueueImageDeletion is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) TryQueueImageDeletion() *MockTaskService_TryQueueImageDeletion_Call {
	return &MockTaskService_TryQueueImageDeletion_Call{Call: _e.mock.On("TryQueueImageDeletion")}
}

func (_c *MockTaskService_TryQueueImageDeletion_Call) Run(run func()) *MockTaskService_TryQueueImageDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_TryQueueImageDeletion_Call) Return(_a0 bool) *MockTaskService_TryQueueImageDeletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_TryQueueImageDeletion_Call) RunAndReturn(run func() bool) *MockTaskService_TryQueueImageDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// TryQueueVideoConversion provides a mock function with no fields
func (_m *MockTaskService) TryQueueVideoConversion() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TryQueueVideoConversion")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_TryQueueVideoConversion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryQueueVideoConversion'
type MockTaskService_TryQueueVideoConversion_Call struct {
	*mock.Call
}

// TryQueueVideoConversion is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) TryQueueVideoConversion() *MockTaskService_TryQueueVideoConversion_Call {
	return &MockTaskService_TryQueueVideoConversion_Call{Call: _e.mock.On("TryQueueVideoConversion")}
}

func (_c *MockTaskService_TryQueueVideoConversion_Call) Run(run func()) *MockTaskService_TryQueueVideoConversion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_TryQueueVideoConversion_Call) Return(_a0 bool) *MockTaskService_TryQueueVideoConversion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_TryQueueVideoConversion_Call) RunAndReturn(run func() bool) *MockTaskService_TryQueueVideoConversion_Call {
	_c.Call.Return(run)
	return _c
}

// TryQueueVideoDeletion provides a mock function with no fields
func (_m *MockTaskService) TryQueueVideoDeletion() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TryQueueVideoDeletion")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_TryQueueVideoDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryQueueVideoDeletion'
type MockTaskService_TryQueueVideoDeletion_Call struct {
	*mock.Call
}

// TryQueueVideoDeletion is a helper method to define mock.On call
func (_e *MockTaskService_Expecter) TryQueueVideoDeletion() *MockTaskService_TryQueueVideoDeletion_Call {
	return &MockTaskService_TryQueueVideoDeletion_Call{Call: _e.mock.On("TryQueueVideoDeletion")}
}

func (_c *MockTaskService_TryQueueVideoDeletion_Call) Run(run func()) *MockTaskService_TryQueueVideoDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskService_TryQueueVideoDeletion_Call) Return(_a0 bool) *MockTaskService_TryQueueVideoDeletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_TryQueueVideoDeletion_Call) RunAndReturn(run func() bool) *MockTaskService_TryQueueVideoDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
