env: "local" # local, dev, prod
database:
  dsn: "postgresql://app:secret@converter-pg:5432/app?sslmode=disable"
  # user: "app"
  # password: "secret"
  # db: "app"
  # host: "converter-pg"
  # port: "5432"
http_server:
  address: "0.0.0.0:80"
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout: 60s
task:
  check_timeout: 5m
image:
  default_formats:
    - ext: "webp"
video:
  default_formats: 
    - ext: "webm"
      optional:
        replace_orig_ext: true
      conv_conf:
        c:v: "libvpx-vp9"
        c:a: "libopus"
        crf: "40"
  threads: 4
