env: "local" # local, dev, prod
postgres:
  # url: "postgresql://app:secret@localhost:5432/app?sslmode=disable"
  user: "app"
  password: "secret"
  db: "app"
  host: "localhost"
  port: "5432"
http_server:
  address: "localhost:8080"
  read_timeout: 4s
  idle_timeout: 60s