env: "local" # local, dev, prod
database:
  dsn: "postgresql://app:secret@converter-pg:5432/app?sslmode=disable"
  # user: "app"
  # password: "secret"
  # db: "app"
  # host: "converter-pg"
  # port: "5432"
http_server:
  address: "0.0.0.0:8080"
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout: 60s
task:
  check_timeout: 5s
image:
  default_formats: "webp"
  # default_formats: "webp?quality=80,avif?quality=80"
video:
  default_formats: "webm?c:v=libvpx-vp9&c:a=libopus&b:v=1M&b:a=128k"
  # default_formats: "webm?video_codec=vp9&audio_codec=opus,mp4?video_codec=h264&audio_codec=aac"
