env: "local" # local, dev, prod
database:
  dsn: "postgresql://app:secret@converter-pg:5432/app?sslmode=disable"
  # user: "app"
  # password: "secret"
  # db: "app"
  # host: "converter-pg"
  # port: "5432"
http_server:
  address: "0.0.0.0:8080"
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout: 60s
task:
  check_timeout: 5s