env: "local" # local, dev, prod
database:
  dsn: "postgresql://app:secret@converter-pg:5432/app?sslmode=disable"
http_server:
  address: "0.0.0.0:80"
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout: 60s
task:
  check_timeout: 5m
image:
  threads: 4
video:
  threads: 4
