// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/chistyakoviv/converter/internal/model"
)

// MockConverter is an autogenerated mock type for the Converter type
type MockConverter struct {
	mock.Mock
}

type MockConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConverter) EXPECT() *MockConverter_Expecter {
	return &MockConverter_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function with given fields: ctx, info
func (_m *MockConverter) Convert(ctx context.Context, info *model.Conversion) error {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Conversion) error); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConverter_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MockConverter_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - ctx context.Context
//   - info *model.Conversion
func (_e *MockConverter_Expecter) Convert(ctx interface{}, info interface{}) *MockConverter_Convert_Call {
	return &MockConverter_Convert_Call{Call: _e.mock.On("Convert", ctx, info)}
}

func (_c *MockConverter_Convert_Call) Run(run func(ctx context.Context, info *model.Conversion)) *MockConverter_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Conversion))
	})
	return _c
}

func (_c *MockConverter_Convert_Call) Return(_a0 error) *MockConverter_Convert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConverter_Convert_Call) RunAndReturn(run func(context.Context, *model.Conversion) error) *MockConverter_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConverter creates a new instance of MockConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConverter {
	mock := &MockConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
