name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.23'
            cache-dependency-path: go.sum

        - name: Install dependencies
          # libaom-dev - AV1 Video Codec Library
          # libheif-dev = HEIF file format decoder
          # see https://github.com/jcupitt/docker-builds/blob/master/libvips-ubuntu18.04/Dockerfile
          run: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common build-essential pkg-config libvips-dev
            sudo apt-get install -y glib-2.0-dev libheif-dev libexpat-dev librsvg2-dev libpng-dev libgif-dev libjpeg-dev libtiff-dev libexif-dev liblcms2-dev liborc-dev libffi-dev
            sudo apt-get install -y libaom-dev ffmpeg

        - name: Verify installation
          run: |
            vips --version
            vips -l
            ffmpeg -version
            pkg-config libheif --print-variables
            pwd
            vips copy internal/converter/govips/tests/files/images/gen.jpg internal/converter/govips/tests/files/images/gen.avif

        - name: Build Converter
          run: go build -o ./bin/ -v ./...

        - name: Test Converter
          run: go test -v ./...

  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint converter
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.62

          # Optional: working directory, useful for monorepos
          # working-directory: ./subdir

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          args: --timeout=30m --config=./.golangci.pipeline.yaml --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"